### ISSUE TITLE
RuntimeException when testing ListPreference

### ISSUE THREAD

**Issue by guillaume-tgl** [robolectric/robolectric#1850]
I'm trying to unit test my `PreferenceFragment` with Robolectric 3.0-RC3. My preferences are defined in a `preferences.xml` file and there are several `ListPreference`.

When I start testing my fragment with `FragmentTestUtil.startFragment(fragment)`, the method `addPreferencesFromResource(R.xml.preferences)` is called in the `onCreate` method of my `PreferenceFragment`.

And I get the following exception:

Caused by: java.lang.RuntimeException: huh? ResName{com.myapp:array/pageOrientation_entries} at     org.robolectric.shadows.Converter.convertAndFill(Converter.java:99) at org.robolectric.shadows.Converter.convertAndFill(Converter.java:50) at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:232) at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:209) at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:55) at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:485) at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java) at android.content.Context.obtainStyledAttributes(Context.java:472) at android.preference.ListPreference.constructor(ListPreference.java:49) at android.preference.ListPreference.(ListPreference.java) at android.preference.GenericInflater.createItem(GenericInflater.java:383) at android.preference.GenericInflater.onCreateItem(GenericInflater.java:417) at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:428) at android.preference.GenericInflater.rInflate(GenericInflater.java:481) at android.preference.GenericInflater.rInflate(GenericInflater.java:493) at android.preference.GenericInflater.inflate(GenericInflater.java:326) at android.preference.GenericInflater.inflate(GenericInflater.java:263) at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272) at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:299) at com.myapp.ui.settings.SettingsFragment.onCreate(SettingsFragment.java:53) at android.app.Fragment.performCreate(Fragment.java:2031) at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:863) at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067) at android.app.BackStackRecord.run(BackStackRecord.java:833) at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452) at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:130) at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:29) at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:95) at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:230) at org.robolectric.util.Scheduler.postAtFrontOfQueue(Scheduler.java:98) at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:114) at android.os.MessageQueue.enqueueMessage(MessageQueue.java) at android.os.Handler.enqueueMessage(Handler.java:631) at android.os.Handler.sendMessageAtTime(Handler.java:600) at android.os.Handler.sendMessageDelayed(Handler.java:570) at android.os.Handler.post(Handler.java:326) at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1358) at android.app.BackStackRecord.commitInternal(BackStackRecord.java:728) at android.app.BackStackRecord.commit(BackStackRecord.java:704) at org.robolectric.util.FragmentTestUtil.startFragment(FragmentTestUtil.java:14) at com.myapp.ui.settings.SettingsFragmentTest.startFragment(SettingsFragmentTest.java:40) at com.myapp.ui.settings.SettingsFragmentTest.plusFeaturesDisabled_onSignaturePrefClick(SettingsFragmentTest.java:70) ... 18 more

When I comment out all the `ListPreference` and leave the other kinds of preferences, I don't have this issue.

Thanks for your help.

**Comment by lexs** [comment]
It's possible this was fixed by https://github.com/robolectric/robolectric/pull/1847 and https://github.com/robolectric/robolectric/pull/1851, especially if it worked in rc2.

**Comment by guillaume-tgl** [comment]
I've just tried rc2, I also have the same issue.
It looks like the `Converter.convertAndFill` method doesn't know how to handle array resources: 
```java    
        if (resName.type.equals("id")) {
          return;
        } else if (resName.type.equals("layout")) {
          return; // resourceId is good enough, right?
        } else if (resName.type.equals("dimen")) {
          return;
        } else if (resName.type.equals("transition")) {
          return;
        } else if (resName.type.equals("interpolator")) {
          return;
        } else if (DrawableResourceLoader.isStillHandledHere(resName)) {
          // wtf. color and drawable references reference are all kinds of stupid.
          ...
        } else {
          throw new RuntimeException("huh? " + resName);
        }
```

**Comment by guillaume-tgl** [comment]
I've just tried version 3.0 and the issue is still here. Any update about this?

**Comment by xian** [comment]
Dupe of #2064.
