### ISSUE TITLE
Robolectric can't find AndroidManifest.xml when testing multidimensional flavor project on Ubuntu

### ISSUE THREAD

**Issue by ivanthai** [robolectric/robolectric#1936]
I have a multidimensional flavor project that I am trying to test with Robolectric 3.0 with the RobolectricGradleTestRunner

```
flavorDimensions 'dimenA', 'dimenB'

android {
    productFlavors {
        foo {
            dimension 'dimenA'
        }
        dev {
            dimension 'dimenB'
        }
    }
}
```

Running Robolectric tests work on OSX. However, when I run the tests on Ubuntu, I get this error:

```
java.io.FileNotFoundException: build/intermediates/manifests/full/fooDev/debug/AndroidManifest.xml (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at org.robolectric.res.FileFsFile.getInputStream(FileFsFile.java:78)
    at org.robolectric.manifest.AndroidManifest.parseAndroidManifest(AndroidManifest.java:131)
    at org.robolectric.manifest.AndroidManifest.getTargetSdkVersion(AndroidManifest.java:445)
    at org.robolectric.RobolectricTestRunner.pickSdkVersion(RobolectricTestRunner.java:430)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:184)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

It is trying to look for the full manifest in `build/intermediates/manifests/full/fooDev/debug/AndroidManifest.xml`

But my full manifest is actually in:
`build/intermediates/manifests/full/foodev/debug/AndroidManifest.xml`

So for some reason, the gradle test runner is trying to find a camel-cased multiflavor name when the Gradle Android plugin generated an all-lower-case multiflavor name

I had to side step the issue by creating a CustomRobolectricGradleTestRunner

```
private static String getFlavor(Config config) {
        try {
            String ret = ReflectionHelpers.getStaticField(config.constants(), "FLAVOR");
            return ret.toLowerCase();
        } catch (Throwable e) {
            return null;
        }
    }
}
```

Android Gradle plugin has always generated all lowercase multiflavor name build directories for multidimensional flavors for me.

FWIW, both my OSX and Ubuntu filesystems are case sensitive, so I'm not exactly sure why it works on OSX and not on Ubuntu

I'm not exactly sure what the right fix should be or if I'm doing something wrong. Maybe Android Gradle needs to be more consistent by generating camel-case multiflavor build directories or Robolectric needs to grab the correct flavor name? Let me know what you think. Thanks!

**Comment by erd** [comment]
> Maybe Android Gradle needs to be more consistent by generating camel-case multiflavor build directories or Robolectric needs to grab the correct flavor name? Let me know what you think. Thanks!

What does your `BuildConfig` look like?

**Comment by ivanthai** [comment]
```
public final class BuildConfig {
  public static final boolean DEBUG = Boolean.parseBoolean("true");
  public static final String APPLICATION_ID = "com.foo.test";
  public static final String BUILD_TYPE = "debug";
  public static final String FLAVOR = "fooDev";
  public static final int VERSION_CODE = 9500;
  public static final String VERSION_NAME = "9.5.0";
  public static final String FLAVOR_dimenA = "foo";
  public static final String FLAVOR_dimenB = "dev";
}
```

**Comment by ivanthai** [comment]
Sorry I meant to say both my OSX and ubuntu file systems are **case sensitive**.

**Comment by subliz** [comment]
I have this problem whit android studio in Windows.

RobolectricGradleTestRunner fails to find AndroidManifest.xml and throws this exception:

    java.lang.RuntimeException: java.lang.RuntimeException: build\intermediates\bundles\debug\AndroidManifest.xml not found or not a file; it should point to your project's AndroidManifest.xml.

I tried to add JUnit tests to a my AS project (using Robolectric 3.0-rc3) and found that the runner fails because it cannot find a manifest in the intermediate files.

The problem, looking at the getAppManifest code is that it checks if a 'manifests' directory exists in intermediates, and if it does, it assumes that intermediates/manifests/full/{buildflavour}/androidManifest.xml must exist and sets the manifest path to that, otherwise fall back to setting it to a file in the bundles directory.

The 
    intermediates/manifests/full/{buildflavour}/androidManifest.xml 
exists in my project but the
    FileFsFile.from(BUILD_OUTPUT, "manifests").exists() 
in RobolectricGradleTestRunner class return false.

I can upload my sample project which can produce the problem if you want.

![5](https://cloud.githubusercontent.com/assets/4850625/8632301/1dc3c8d4-27aa-11e5-961d-15af1621adf2.png)

![6](https://cloud.githubusercontent.com/assets/4850625/8632302/1f7c1776-27aa-11e5-9d52-30973ca6c35f.png)

**Comment by erd** [comment]
> public static final String FLAVOR = "fooDev";

We're grabbing the flavor name from the build config, so if it's camel-case in your `BuildConfig` it should be camel-case on the filesystem. Maybe it's worth asking about on `adt-dev@googlegroups.com` (I think that's the mailing list for the tools team)?

**Comment by erd** [comment]
> I can upload my sample project which can produce the problem if you want.

That would be great!

**Comment by ivanthai** [comment]
Thanks, I am asking them and will update you

**Comment by ivanthai** [comment]
Looks like they will reach out to you guys?

https://code.google.com/p/android/issues/detail?id=180112

**Comment by jaredsburrows** [comment]
@erd @ivanthai  Did you ever upload your example project?

**Comment by rlac** [comment]
Version 1.5.0 of the Gradle build plugin now generates camel case direcotry names for multi-dimensional flavour build directories.

This is causing the opposite issue originally reported here - Robolectric 3.0 is expecting lowercase directory names, so my tests are now failing with errors like `"build/intermediates/res/merged/foodev/debug/values is not a directory"` - where the directory is now `"build/intermediates/res/merged/fooDev/debug/values"`.

**Comment by athkalia** [comment]
@subliz I am facing the exact same problem in windows. Did you manage to solve it?

**Comment by athkalia** [comment]
My problem was with the Intellij 16 eap that has a bug on it's $MODULE_DIR$ variable. See https://youtrack.jetbrains.com/issue/IDEA-149802#tab=History. Will get fixed in build 144.2637

**Comment by jpd236** [comment]
I'm using Android Gradle plugin v2.2.3 and still see this inconsistency. GradleManifestFactory is pulling the FLAVOR constant from the build config which is camel cased, but the merged manifest in the output directory is all lower case.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
