### ISSUE TITLE
Issue in robolectric 3.1 and 3.1.1 librray

### ISSUE THREAD

**Issue by lalitrcm** [robolectric/robolectric#2564]
### Description
Using the following gradle library to build the robolectric test cases.
`testCompile 'org.robolectric:robolectric:3.1'`
`testCompile 'org.robolectric:shadows-multidex:3.1'`

Suddenly the Jenkin build was started failing from **July 12, 2016** by throwing the below logs.

Unable to resolve artifact: Missing:
1) org.robolectric:android-all:jar:5.1.1_r9-robolectric-1

Try downloading the file manually from the project website.
Then, install it using the command: 
	mvn install:install-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=5.1.1_r9-robolectric-1 -Dpackaging=jar -Dfile=/path/to/file

Alternatively, if you host your own repository you can deploy the file there: 
	mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=5.1.1_r9-robolectric-1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

Path to dependency: 
	1) org.apache.maven:super-pom:pom:2.0
	2) org.robolectric:android-all:jar:5.1.1_r9-robolectric-1

2) org.robolectric:shadows-core:jar:22:3.1

Try downloading the file manually from the project website.

Then, install it using the command: 
	mvn install:install-file -DgroupId=org.robolectric -DartifactId=shadows-core -Dversion=3.1 -Dclassifier=22 -Dpackaging=jar -Dfile=/path/to/file

Alternatively, if you host your own repository you can deploy the file there: 
		mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=shadows-core -Dversion=3.1 -Dclassifier=22 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

Path to dependency: 
	1) org.apache.maven:super-pom:pom:2.0
	2) org.robolectric:shadows-core:jar:22:3.1

2 required artifacts are missing.
for artifact: 
	org.apache.maven:super-pom:pom:2.0

### Steps to Reproduce
Then as a next step I took the latest maven build from following repos
https://mvnrepository.com/artifact/org.robolectric/shadows-multidex/3.1.1
https://mvnrepository.com/artifact/org.robolectric/robolectric/3.1.1

`testCompile 'org.robolectric:robolectric:3.1.1'`
`testCompile 'org.robolectric:shadows-multidex:3.1.1'`

But now the build is giving syncing issue
Error:Module 'org.robolectric:shadows-multidex:3.1.1' depends on one or more Android Libraries but is a jar
 
### Robolectric & Android Version
`testCompile 'org.robolectric:robolectric:3.1'`
`testCompile 'org.robolectric:shadows-multidex:3.1'`

`compileSdkVersion 23`
`buildToolsVersion "23.0.2"`

**Comment by xian** [comment]
I'm not able to reproduce this; are you still having this issue @lalitrcm?

**Comment by jongerrish** [comment]
Think it's fixed at head now.

**Comment by lalitrcm** [comment]
@jongerrish 

I am using these versions in the build.gradle file.
` testCompile 'org.robolectric:robolectric:3.1.1'`
` testCompile 'org.robolectric:shadows-multidex:3.1.1'`

But still getting the sync issue
Error:Module 'org.robolectric:shadows-multidex:3.1.1' depends on one or more Android Libraries but is a jar

**Comment by lalitrcm** [comment]
@xian 
While using the below versions in the build.gradle file
testCompile 'org.robolectric:robolectric:3.1.1'
testCompile 'org.robolectric:shadows-multidex:3.1.1'

Studio giving sync issue as below
> Error:Module 'org.robolectric:shadows-multidex:3.1.1' depends on one or more Android Libraries but is a jar

Whether I need to add any other libraries as part of testCompile?
OR
Whether I need to exclude some groups from the current 3.1.1 library.

**Xian**, It may be the below scenario why it is not reproducible in your machine. 
> The version 3.1.1 and its dependencies was already cached in the local .m2 directory on the system.
I observed this as a scenario when playing with some other libraries. The application is getting failed in JENKIN server because of unable to resolve dependencies but working successfully in local studio.
Might be you have tried this scenario as well.

Please let me know if you need any other information to come to a conclusion as the Unit Test Code Coverage report generation is completely blocked from last week.

**Comment by lalitrcm** [comment]
Hi Robolectric Team,

Please look into the below issue that again we are facing while executing the robolectric test cases in Jenkin.
> Caused by:
         org.apache.maven.artifact.resolver.MultipleArtifactsNotFoundException: Missing:
         ----------
         1) org.robolectric:android-all:jar:5.1.1_r9-robolectric-1
 
           Try downloading the file manually from the project website.
 
           Then, install it using the command: 
               mvn install:install-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=5.1.1_r9-robolectric-1 -Dpackaging=jar -Dfile=/path/to/file
 
           Alternatively, if you host your own repository you can deploy the file there: 
               mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=5.1.1_r9-robolectric-1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
 
           Path to dependency: 
           	1) org.apache.maven:super-pom:pom:2.0
           	2) org.robolectric:android-all:jar:5.1.1_r9-robolectric-1
 
         2) org.robolectric:shadows-core:jar:22:3.1
 
           Try downloading the file manually from the project website.
 
           Then, install it using the command: 
               mvn install:install-file -DgroupId=org.robolectric -DartifactId=shadows-core -Dversion=3.1 -Dclassifier=22 -Dpackaging=jar -Dfile=/path/to/file
 
           Alternatively, if you host your own repository you can deploy the file there: 
               mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=shadows-core -Dversion=3.1 -Dclassifier=22 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
 
           Path to dependency: 
           	1) org.apache.maven:super-pom:pom:2.0
           	2) org.robolectric:shadows-core:jar:22:3.1
 
         ----------
         2 required artifacts are missing.
 
         for artifact: 
           org.apache.maven:super-pom:pom:2.0

Please help us to identify the issue and resolve ASAP as we are almost blocked again to generate test case report from yesterday.
