### ISSUE TITLE
Upgrading Robolectric Test from Android Studio 2.4 to 3.0 caused NPE.

### ISSUE THREAD

**Issue by elye** [robolectric/robolectric#3216]
### Description
https://stackoverflow.com/questions/44838714/robolectric-npe-when-migrate-from-android-studio-2-4-to-3-0

### Steps to Reproduce
Create a simple project from Android Studio 3.0 (Canary 5).
Then in the test make it a robolectric test

```
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, sdk = LOLLIPOP, packageName="your.package)
```

Then run it.

It will crash with

    java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:332)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:259)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:41)

### Robolectric & Android Version
I'm using ` testImplementation 'org.robolectric:robolectric:3.2.2'`
Android version could be any version. Android Studio 3.0

Suspect the fix in https://github.com/robolectric/robolectric/pull/3158/files could fix the issue.

**Comment by DCRichards** [comment]
What's the progress of this @jongerrish? 3.5.1 is now out, was this fixed in 3.4.1?

**Comment by Abdul-Hannan** [comment]
13 November 2017: 
Seems like Roboelectric is still not compatible with Android Studio 3

**Comment by jongerrish** [comment]
Yes, this is working with the following caveats:-

For library modules, Manifest + Assets are not merged, (note: assets and manifests have never been merged in Robolectric)

Here are the instructions to use AS 3.0:-

http://robolectric.org/getting-started/

Note: You need to remove constants = BuildConfig.class otherwise this falls back to the hacky AS2.3 integration
