### ISSUE TITLE
RuntimeException inflating a layout that contains @font resource reference

### ISSUE THREAD

**Issue by lyricsboy** [robolectric/robolectric#3390]
### Description

I'm using a custom font resource, [added in Oreo](https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml.html) and using the `support-compat` library to make it backwards compatible. It works fine at runtime, but in tests, trying to inflate a layout with a `@font/foo` reference in it blows up with the following:

```
android.view.InflateException: XML file .../app/build/intermediates/merged-not-compiled-resources/staging/debug/layout/error_overlay.xml line #-1 (sorry, not yet implemented): XML file .../app/build/intermediates/merged-not-compiled-resources/staging/debug/layout/error_overlay.xml line #-1 (sorry, not yet implemented): Error inflating class TextView

Caused by: android.view.InflateException: XML file .../app/build/intermediates/merged-not-compiled-resources/staging/debug/layout/error_overlay.xml line #-1 (sorry, not yet implemented): Error inflating class TextView
Caused by: java.lang.RuntimeException: huh? ResName{com.myapp:font/font_name}
	at org.robolectric.shadows.ShadowAssetManager.convertAndFill(ShadowAssetManager.java:156)

```

Idea: could the implementation of `ShadowAssetManager.buildTypedValue` be modified to catch exceptions from `convertAndFill` and log + return null? Or something similar that would make Robolectric just ignore things that it doesn't (yet) understand?

The net effect of the current behavior is that:

1. I can't write a Robolectric test that inflates a layout containing an unsupported resource reference
1. Therefore I can't test my custom view that inflates that layout

### Robolectric & Android Version

Robolectric 3.4.2
Android 26, build tools 26.0.1

**Comment by davidgoli** [comment]
It looks like this was fixed in 0abb30427e09ab7adcff804e48dcd82dd375eee0, however, that has not yet been released. Can we get a new release for this? Robolectric is the only hangup left to using XML fonts in Oreo - even AppCompatTextView backports support for this.

**Comment by dwb357** [comment]
This problem doesn't just occur with Fonts.  I'm also seeing it with Progress bar.  The following generates a virtually identical error message:

`                <ProgressBar
                    style="?android:attr/progressBarStyleLarge"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:id="@+id/progressBar"
                    android:indeterminate="true"
                    android:layout_gravity="center"
                    android:focusableInTouchMode="true"
                    android:layout_marginBottom="15dp"
                    />
`

although only when used in conjunction with run tests with coverage.

**Comment by zafrani** [comment]
I still have this problem with my fonts in Robolectric 3.6.1, Android 27 and build tools 27.0.1

**Comment by jongerrish** [comment]
Try Robolectric 4.0 - we have support for binary resources now.... This has
fixed a bunch of resources issues as the implementation is transliterated
framework C code into Java.

It's also showing a ~25% performance improvement too.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.

**Comment by ElizAWard** [comment]
> We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.
> 
> Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-
> 
> ```groovy
> testImplementation "org.robolectric:robolectric:4.0"
> 
> android {
>   enableUnitTestBinaryResources=true
>   testOptions {
>     unitTests {
>       includeAndroidResources = true
>     }
>   }
> }
> ```
> 
> We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.
> 
> If this is still an issue an example project with failing test would be most helpful.

I just tried to add the enableUnitTestBinaryResources=true
but Android Studio says "Could not set unknown property 'enableUnitTestBinaryResources' for object of type com.android.build.gradle.AppExtension."

I am pointing to robolectric 4.0

**Comment by jongerrish** [comment]
What version of studio are you using?

**Comment by xian** [comment]
`enableUnitTestBinaryResources=true` goes in your `gradle.properties`.

**Comment by ElizAWard** [comment]
Android Studio 3.1.2

**Comment by jongerrish** [comment]
Can you try putting that value in your gradle.properties and trying again?
