### ISSUE TITLE
Robolectric 4 does not work on Windows

### ISSUE THREAD

**Issue by radzio** [robolectric/robolectric#3955]
### Description
Robolectric 4  does not work with @RunWith(AndroidJUnit4::class) on Windows, but works on macOS

### Steps to Reproduce

1. Clone: https://github.com/cdsap/TestRobolectric4 and update Gradle plugin to the latest version
2. Run `MainActivityTest` from the Android Studio
3. expected behavior: the test is executed

Current behavior on Windows: exception is thrown with info:
`Illegal character in opaque part at index 11: jar:file:C:\Users\rados\Downloads\TestRobolectric4-master\app\build\intermediates\apk_for_local_test\debugUnitTest\packageDebugUnitTestForUnitTest\apk-for-local-test.ap_`

### Robolectric & Android Version
Robolectric:
4.0-alpha-1, 4.0-alpha-2

Android Studio 3.2.0 beta 3

### Link to a public git repo demonstrating the problem:
https://github.com/cdsap/TestRobolectric4

Issue was reported to the Google team too: https://issuetracker.google.com/issues/111345016

**Comment by johannesplanis** [comment]
Also failing on the latest Alpha:

Android Studio 3.3.0 Alpha 2
Gradle plugin 3.3.0 Alpha 2
Windows 10 64bit 

I used project from the same repo and when I have run MainActivity the following exception was thrown:
java.lang.RuntimeException: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/my_username/.m2/repository/org/robolectric/android-all/8.1.0-robolectric-4611349/android-all-8.1.0-robolectric-4611349.jar

**Comment by christopherfrieler** [comment]
Just ran into this issue.
The problem seems to come from [https://android.googlesource.com/platform/tools/base/+/studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/internal/tasks/PackageForUnitTest.java#58](https://android.googlesource.com/platform/tools/base/+/studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/internal/tasks/PackageForUnitTest.java#58). Backslashes are not handled correctly and end up in the URI.

**Comment by NeverwinterMoon** [comment]
> After I've removed `android.enableUnitTestBinaryResources=true` it works on Windows.

This gives a whole bunch of warnings though (as I understand they are related to not using the `enableUnitTestBinaryResources` option): `[Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40`. Which is extremely annoying.

**Comment by NickButcher1** [comment]
Same issue for me.  I can't use `android.enableUnitTestBinaryResources=true` on Windows because of:

```
Execution failed for task ':app:packageDebugUnitTestForUnitTest'.
> Illegal character in opaque part at index 11: jar:file:C:\code\max\app\build\intermediates\apk_for_local_test\debugUnitTest\packageDebugUnitTestForUnitTest\apk-for-local-test.ap_
```

Robolectric 4.0.1, Android Gradle Plugin 3.2.1, Windows 10 64bit.

**Comment by fbattet** [comment]
Same issue for me.
Robolectric 4.0.1, Android Gradle Plugin 3.2.0, Windows 10 64bit.

**Comment by nohum** [comment]
I have the same problem on one of our development machines (both running Ubuntu Linux actually). On the machine were it is working the full path to the project does not contain spaces.

On the failing machine we get the same error message: `Illegal character in opaque part at index X: jar:file:...` where `X` marks the space in the file path to the project where the first space is occuring.

This only happens if `android.enableUnitTestBinaryResources=true` is added in `gradle.properties` for us. Removing it makes the tests run again.

**Comment by m00head** [comment]
https://github.com/robolectric/robolectric/issues/4082#issuecomment-436409454
> @rameshmkll Yep, we'll have a fix in 4.0.2 for binary resources on windows.

**Comment by xian** [comment]
This should be fixed in current AGP 3.3 betas (https://developer.android.com/studio/preview/) — please reopen this issue if not. Thanks!

**Comment by rameshmkll** [comment]
Still getting the same error in AndroidStudio 3.0 Beta 3

**Comment by xian** [comment]
@rameshmkll — did you mean Android Studio 3.0 beta 3 or a 3.3 beta?

**Comment by hameno** [comment]
Still failing with 3.3.0-beta03:
RuntimeException: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/<USER>/.m2/repository/org/robolectric/android-all/5.0.2_r3-robolectric-r0/android-all-5.0.2_r3-robolectric-r0.jar

**Comment by hameno** [comment]
Still failing on 3.3.0-beta03:
java.lang.RuntimeException: java.lang.RuntimeException: Failed to parse package C:\<project>\build\intermediates\apk_for_local_test\debugUnitTest\packageDebugUnitTestForUnitTest\apk-for-local-test.ap_: Unable to read AndroidManifest.xml of C:\<project>\build\intermediates\apk_for_local_test\debugUnitTest\packageDebugUnitTestForUnitTest\apk-for-local-test.ap_
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/<USER>/.m2/repository/org/robolectric/android-all/4.2.2_r1.2-robolectric-r1/android-all-4.2.2_r1.2-robolectric-r1.ja

**Comment by xian** [comment]
@hameno — could you include a stack trace?

**Comment by qwertyfinger** [comment]
@xian I was experiencing this issue on both OS X and Windows with AGP 3.2.1 but with AGP 3.3.0-beta03 everything works fine.

**Comment by rameshmkll** [comment]
My Test cases are running successfully after i have  removed 
"android.enableUnitTestBinaryResources=true" from gradle.properties in Android studio 3.3 beta 3.

**Comment by xian** [comment]
@rameshmkll — unfortunately your tests will run in the old, deprecated resources mode if you remove `android.enableUnitTestBinaryResources=true`. Could you try putting it back and paste the resulting stack trace here so we can fix it? Thanks!

**Comment by mpost** [comment]
I am also seeing the same exception on Windows running Android Studio `3.3-beta4` with AGP `3.4.0-alpha2`. I have set `android.enableUnitTestBinaryResources=true` and set the compileSdk to 28. Setting binary resource false also works on the machine.

```java
java.lang.RuntimeException: android.content.pm.PackageParser$PackageParserException: Failed to parse C:\Users\mpost\git\project\module\build\intermediates\apk_for_local_test\debugUnitTest\packageDebugUnitTestForUnitTest\apk-for-local-test.ap_

	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:57)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:150)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:377)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:252)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:104)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: android.content.pm.PackageParser$PackageParserException: Failed to parse C:\Users\mpost\git\project\module\build\intermediates\apk_for_local_test\debugUnitTest\packageDebugUnitTestForUnitTest\apk-for-local-test.ap_
	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1760)
	at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:886)
	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1274)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1009)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1029)
	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:31)
	... 18 more
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/mpost/.m2/repository/org/robolectric/android-all/8.1.0-robolectric-4611349/android-all-8.1.0-robolectric-4611349.jar
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.robolectric.res.android.CppAssetManager.getFileModDate(CppAssetManager.java:1755)
	at org.robolectric.res.android.CppAssetManager.access$000(CppAssetManager.java:38)
	at org.robolectric.res.android.CppAssetManager$SharedZip.get(CppAssetManager.java:1507)
	at org.robolectric.res.android.CppAssetManager$SharedZip.get(CppAssetManager.java:1502)
	at org.robolectric.res.android.CppAssetManager$ZipSet.getZipResourceTable(CppAssetManager.java:1680)
	at org.robolectric.res.android.CppAssetManager.appendPathToResTable_measured(CppAssetManager.java:618)
	at org.robolectric.res.android.CppAssetManager.lambda$appendPathToResTable$0(CppAssetManager.java:572)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.res.android.CppAssetManager.appendPathToResTable(CppAssetManager.java:570)
	at org.robolectric.res.android.CppAssetManager.lambda$getResTable$1(CppAssetManager.java:711)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:72)
	at org.robolectric.res.android.CppAssetManager.getResTable(CppAssetManager.java:704)
	at org.robolectric.res.android.CppAssetManager.getResources(CppAssetManager.java:812)
	at org.robolectric.res.android.CppAssetManager.getResources(CppAssetManager.java:808)
	at org.robolectric.shadows.ShadowArscAssetManager.getStringBlockCount(ShadowArscAssetManager.java:1314)
	at android.content.res.AssetManager.getStringBlockCount(AssetManager.java)
	at android.content.res.AssetManager.makeStringBlocks(AssetManager.java:316)
	at android.content.res.AssetManager.addAssetPathInternal(AssetManager.java:690)
	at android.content.res.AssetManager.addAssetPath(AssetManager.java:674)
	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1726)
	... 23 more
```

**Comment by arild-jacobsen** [comment]
Had the same issue on macos mojave. Problem resolved by upgrading to gradle plugin 3.3.0-rc1.

**Comment by NickButcher1** [comment]
Still broken for me with
Robolectric 4.0.2, Android Gradle Plugin 3.3.0-rc1, Windows 10 64bit.  But it does build on my Linux CI.

**Comment by jongerrish** [comment]
Also on Google Issue Tracker here: https://issuetracker.google.com/120098460

**Comment by caltseng** [comment]
Please add this as a known issue for all the 4.0 releases, as it is implied in the release notes that this only affects 4.0.2 when it actually affects 4.0, 4.0.1, and 4.0.2.

**Comment by sglasman** [comment]
Still encountering this issue with Robolectric 4.1: `java.lang.IllegalArgumentException: Illegal character in opaque part at index 11: jar:file:C:\{path}\apk-for-local-test.ap_`

**Comment by AmrAfifiy** [comment]
We're still encountering another windows paths issue with Robolectric 4.1

`java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/jedo/android-tests/runUnitTese3f8a969a37ef6500582f805697c00bf999d9ee2/unitTestingAndroidResources/build/intermediates/sourceFolderJavaResources/test/debug/../../../../../robolectric-libs/android-all-7.0.0_r1-robolectric-r1.jar`

hungnv@ traced the incorrect path to this line: https://github.com/robolectric/robolectric/blob/d7c10e6ae373334b1b37f5b8539ee11585dbf072/robolectric/src/main/java/org/robolectric/android/internal/AndroidEnvironment.java#L103

Please revert to https://issuetracker.google.com/123772179 and https://issuetracker.google.com/120098460 for the full stacktrace.

**Comment by NeverwinterMoon** [comment]
@spacemase Are you talking about the "Fix more dumb windows bugs"? I think it refers to the bugs being dumb - as in they are so obvious, they shouldn't have been made in the first place. I don't think the OS was called dumb...

**Comment by xian** [comment]
@spacemase pull requests gladly accepted.

**Comment by spacemase** [comment]
@xian do grow up

**Comment by xian** [comment]
This should be fixed in 4.2.1: https://github.com/robolectric/robolectric/releases/tag/robolectric-4.2.1

Please reopen if not. Thanks!

**Comment by peassuncao** [comment]
I tested on gradle-5.4.1
And
setting classpath 'com.android.tools.build:gradle:3.4.0'
and it worked

**Comment by dmykhailenko** [comment]
After update of Robolectric from the version `3.5.1` to `4.3-beta-1` unit tests in a project completely stopped executing on Windows environment. Linux and MacOs systems are not affected. 
Here are the details of the issue:
__The exception__
> Exception in thread "SharedPreferencesImpl-load" java.lang.RuntimeException: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
> 	at org.robolectric.shadows.OsConstantsValues.canonicalize(OsConstantsValues.java:60)
> 	at org.robolectric.shadows.OsConstantsValues.getMode(OsConstantsValues.java:50)
> 	at org.robolectric.shadows.ShadowPosix.stat(ShadowPosix.java:23)
> 	at libcore.io.Posix.stat(Posix.java)
> 	at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:293)
> 	at android.system.Os.stat(Os.java:454)
> 	at android.app.SharedPreferencesImpl.loadFromDiskLocked(SharedPreferencesImpl.java:113)
> 	at android.app.SharedPreferencesImpl.access$000(SharedPreferencesImpl.java:51)
> 	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java:90)
> Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
> 	at java.io.WinNTFileSystem.canonicalize0(Native Method)
> 	at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
> 	at java.io.File.getCanonicalPath(File.java:618)
> 	at org.robolectric.shadows.OsConstantsValues.canonicalize(OsConstantsValues.java:58)
> 	at org.robolectric.shadows.OsConstantsValues.getMode(OsConstantsValues.java:50)
> 	at org.robolectric.shadows.ShadowPosix.stat(ShadowPosix.java:23)
> 	at libcore.io.Posix.stat(Posix.java)
> 	at libcore.io.BlockGuardOs.$$robo$$libcore_io_BlockGuardOs$stat(BlockGuardOs.java:293)
> 	at libcore.io.BlockGuardOs.stat(BlockGuardOs.java)
> 	at android.system.Os.$$robo$$android_system_Os$stat(Os.java:454)
> 	at android.system.Os.stat(Os.java)
> 	at android.app.SharedPreferencesImpl.$$robo$$android_app_SharedPreferencesImpl$loadFromDiskLocked(SharedPreferencesImpl.java:113)
> 	at android.app.SharedPreferencesImpl.loadFromDiskLocked(SharedPreferencesImpl.java)
> 	at android.app.SharedPreferencesImpl.access$000(SharedPreferencesImpl.java:51)
> 	at android.app.SharedPreferencesImpl$1.$$robo$$android_app_SharedPreferencesImpl_1$run(SharedPreferencesImpl.java:90)
> 	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java)

__Example of problematic complete file path. Notice colons in a file name.__
`C:\Users\XXXX\AppData\Local\Temp\robolectric-Method_givenNoIdIsStored_whenGetUniqueId_thenGeneratesCorrectId7658193915283748502\com.abcd.mobile.android.dev-dataDir\shared_prefs\io.fabric.sdk.android:fabric:io.fabric.sdk.android.Onboarding.xml`

__A list of all problematic file names I saw during tests debugging__

> com.ocado.mobile.android.dev-dataDir\shared_prefs\io.fabric.sdk.android:fabric:io.fabric.sdk.android.Onboarding.xml
> com.ocado.mobile.android.dev-dataDir\shared_prefs\com.crashlytics.sdk.android:answers:settings.xml
> com.ocado.mobile.android.dev-dataDir\shared_prefs\com.crashlytics.sdk.android.crashlytics-core:com.google.android.gms.measurement.prefs.xml
> com.ocado.mobile.android.dev-dataDir\shared_prefs\com.crashlytics.sdk.android.crashlytics-core:com.crashlytics.android.core.CrashlyticsCore.xml
> com.ocado.mobile.android.dev-dataDir\shared_prefs\com.google.firebase.common.prefs:[DEFAULT].xml

Please ask if you need more info.

**Comment by Kisty** [comment]
@dmykhailenko have you tried rolling back to Robolectric `4.2.1`? And have you updated the latest version of Fabric dependency and its Gradle plugin?

**Comment by dmykhailenko** [comment]
It works normally with Robolectric versions 4.2.1 and 4.3-alpha-2. Stops working with 4.3-alpha-3.
The Gradle Plugin is of version 3.4.1
All dependencies and plugins are at their latest version.

**Comment by krzysiek-zgondek** [comment]
when i'm trying to run newest robolectric (4.3.1) i get NullPointerException right after 'Downloading from maven' message. I did some research and it looks like it's something related to testing android libraries because when i've created new project (normal android app project) and tried running robolectric there it worked and also library tests had started to work.

In the end i have to open normal android project, run any robolectric test and then i can switch to my library project and start testing lib normally.

My guess is that robolectric has a problem obtaining artifacts for com.android.library like projects but it doesn't for com.android.application.

Begging of stack trace:
```
java.lang.NullPointerException
	at org.apache.maven.artifact.ant.AbstractArtifactTask.diagnoseError(AbstractArtifactTask.java:613)
	at org.apache.maven.artifact.ant.AbstractArtifactTask.execute(AbstractArtifactTask.java:755)
	at org.robolectric.internal.dependency.MavenDependencyResolver.whileLocked(MavenDependencyResolver.java:95)
	at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:74)
```
