### ISSUE TITLE
Shadows are not visible with Robolectric native graphics

### ISSUE THREAD

**Issue by oas004** [robolectric/robolectric#8081]
### Description
Might be totally wrong here and feel free to close this issue if so. 

I tried testing out robolectric native graphics(RNG) and making a bitmap from a composable with a Card composable inside it, but in the screenshot I'm not able to render any shadows.

### Steps to Reproduce

You can add a test like this

```kt
 @get:Rule
    val composeTestRule = createComposeRule()

    @get:Rule
    val testName = TestName()

    @OptIn(ExperimentalCoroutinesApi::class)
    @GraphicsMode(GraphicsMode.Mode.NATIVE)
    @Test
    fun cardTest() = runTest {
        lateinit var view: View

        composeTestRule.setContent {
            view = LocalView.current
            SomeCard()
        }

        composeTestRule.awaitIdle()

        val image = Bitmap.createBitmap(
            /* width = */ view.width,
            /* height = */ view.height,
            /* config = */ Bitmap.Config.ARGB_8888
        ).apply {
            view.draw(Canvas(this))
        }
        val path = System.getProperty("user.dir")

        File("$path/src/test/snapshots/images", "${testName.methodName}-screenshot.png")
            .writeBitmap(image, Bitmap.CompressFormat.PNG, 100)

        println("Saved file at $path")
    }


```

Where `SomeCard` is

```kt

@Composable
fun SomeCard() {
    MaterialTheme {
        Box(Modifier.size(300.dp).background(MaterialTheme.colors.background)) {
            Card(
                modifier = Modifier.size(200.dp).align(Alignment.Center),
                backgroundColor = MaterialTheme.color.surface,
                elevation = 8.dp
            ) {
                Column(modifier = Modifier.fillMaxWidth(), horizontalAlignment = Alignment.CenterHorizontally) {
                    Text(
                        text = "Title",
                        style = MaterialTheme.typography.h1
                    )

                    Text(
                        text = "Body",
                        style = MaterialTheme.typography.body1
                    )


                    Button(onClick = {}) {

                        Text(
                            text = "Body",
                            style = MaterialTheme.typography.button
                        )
                    }
                }
            }
        }
    }
}

```

This should have the shadow on the card and the button should have the shadow. This is the result I got from the preview and the snapshot generated:

| Preview from AS  |    Snapshot  from test  |
|----------|:-------------:|
| ![image](https://user-images.githubusercontent.com/54936943/226599683-a2fdbd88-e301-4373-a087-beb4de6baee7.png) | ![image](https://user-images.githubusercontent.com/54936943/226599874-68ca7369-495d-4bde-ab80-b4c169971d2f.png)  |
 
### Robolectric & Android Version

4.10-alpha-1

### Link to a public git repo demonstrating the problem:

Here is sample github repo: https://github.com/oas004/NativeGraphicsSample

Here is link to the test in question: https://github.com/oas004/NativeGraphicsSample/blob/main/app/src/test/java/com/example/nativegraphicssample/CardScreenshotTest.kt

**Comment by hoisie** [comment]
Thanks for the report, we are aware of this issue and are investigating some potential fixes. The underlying issue is that elevation (and some other properties, e.g. clipToOutline) are part of [RenderNode](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/graphics/java/android/graphics/RenderNode.java;l=1044) and they don't get rendered by default when drawing to a SW-backed Canvas. They are rendered onto a HW-backed canvas during the threaded rendering process.

However, I think there are a variety of technical solutions to this, so we are looking into it.

**Comment by hoisie** [comment]
You can keep it open, we can use this as the canonical issue.

The solution to this is to initialize a ThreadedRenderer and attach it to the RenderNode associated with the View that is being rendered.

However, this may have some undefined behavior in RNG right now, as the hardware rendering native code may not be 100% fully working.

**Comment by oas004** [comment]
Okay, is it possible to test that out in the sample I made? :) Not that familiar with the implementation details here, but when you refer to the ThreadedRender is it [this](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/view/ThreadedRenderer.java;l=63?q=ThreadedRen&sq=) ? :)

**Comment by hoisie** [comment]
@oas004 yeah definitely I can take a look at some simple test cases related to HW rendering and see what's happening.

**Comment by hoisie** [comment]
Spent some today looking into this. Looks like this will involve better support for HardwareRender / ImageReader / Surface in RNG. It is definitely doable, and it's something we are prioritizing, but it's hard to get a sense of how long it will take. 

Our general recommendation is that if you require pixel-perfect rendering to stick with emulator-based screenshot tests. If software rendering without drop shadows is sufficient for your use case you can start with that and then when HW rendering code paths are better supported you could switch over to that.

**Comment by utzcoz** [comment]
@hoisie I remember the shadow is implemented in `libhwui`. I analyzed the window shadow before at https://utzcoz.github.io/2020/04/13/Analyze-window-shadow.html. I think RNR contains `libhwui`, because it's the critical library for native graphics.

**Comment by hoisie** [comment]
@utzcoz very cool post :)

RNG does contain include a lot of HWUI, but it only has a fake/minimal implementation of libui and libgui (these are part of the low-level interfaces to surfaceflinger).

In HW rendering Skia APIs are still being used, so the idea is to use HardwareRenderer that writes to Skia, and then capture the underlying Surface buffer using ImageReader.

**Comment by sergio-sastre** [comment]
> @hoisie @utzcoz @oas004 Actually, you can render shadows and elevation by using PixelCopy instead of Canvas, at least on devices.
> 
> Not sure how PixelCopy works in Robolectric, but that would be an option.
> 
> I wrote about that here: https://github.com/sergio-sastre/AndroidUiTestingUtils#bitmap

I just gave it a try, and pixel copy renders exactly the same as Canvas with Robolectric -> No shadows.

However, as I mentioned, there is a subtle difference when using Cnavas and PicelCopy on an emulator/device

**Comment by morux2** [comment]
Hello, does anyone has any update about this?

**Comment by marianeum** [comment]
Is there any update on this? I'm attempting to use roborazzi (https://github.com/takahirom/roborazzi) for snapshot testing and this issue is preventing me from it

**Comment by hoisie** [comment]
@ralf-at-android has made great progress on this. I think it can technically be done with the SNAPSHOT version of Robolectric, but I am not sure roborazzi is wired to support that. Maybe we should do a quick 4.12 release to support HW rendering code paths.

**Comment by marianeum** [comment]
ooh that's great news - i just tried bumping to the snapshot version and that indeed doesn't seem to be supported by roborazzi yet

**Comment by hoisie** [comment]
My guess is that Roborazzi will also need to update the way it generates screenshots. My guess is that it uses Bitmap/Canvas APIs to generate screenshots, but it will need to use HardwareRenderer/ImageReader APIs to get screenshots using the HW rendering paths. Should be similar to this:

https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/HardwareRenderingScreenshot.java

**Comment by sergio-sastre** [comment]
> My guess is that Roborazzi will also need to update the way it generates screenshots. My guess is that it uses Bitmap/Canvas APIs to generate screenshots, but it will need to use HardwareRenderer/ImageReader APIs to get screenshots using the HW rendering paths. Should be similar to this:
> 
> https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/HardwareRenderingScreenshot.java

@takahirom 😉

**Comment by ralf-at-android** [comment]
The best way to get shadows would be to capture using `PixelCopy.Request` instead of `Canvas.draw()`.

ShadowPixelCopy has support for both: it will use hardware rendering if available and otherwise default to canvas:
https://github.com/robolectric/robolectric/blob/29d4adfae16016f6a132d998c5c2b7d7329fdaf3/shadows/framework/src/main/java/org/robolectric/shadows/ShadowPixelCopy.java#L170

**Comment by takahirom** [comment]
Thank you for letting me know. I've just updated Roborazzi to be able to use Pixel Copy as much as possible. I'll release this change today as 1.9.0-alpha-1.

**Comment by hoisie** [comment]
We can also do a 4.12 release that contains all of the latest hardware rendering related fixes.

**Comment by takahirom** [comment]
I'm experiencing a ClassNotFoundException when using Pixel Copy with the snapshot version of Robolectric, specifically when robolectric.screenshot.hwrdr.native=true is set. This issue occurs during testing, resulting in a java.lang.ClassNotFoundException: java.nio.NioUtils error.

For a clearer picture, I've prepared a minimal example demonstrating the issue: [GitHub - takahirom/robolectric-snapshot-class-not-found-reproducer](https://github.com/takahirom/robolectric-snapshot-class-not-found-reproducer).

If there is any additional information I can provide, or if I have misunderstood any aspect of my setup, please let me know.

```
java.lang.NoClassDefFoundError: java/nio/NioUtils
	at android.media.ImageReader$SurfaceImage$SurfacePlane.clearBuffer(ImageReader.java:1389)
	at android.media.ImageReader$SurfaceImage.clearSurfacePlanes(ImageReader.java:1333)
	at android.media.ImageReader.releaseImage(ImageReader.java:690)
	at android.media.ImageReader$SurfaceImage.close(ImageReader.java:1171)
	at android.media.ImageReader.close(ImageReader.java:801)
	at org.robolectric.shadows.HardwareRenderingScreenshot.takeScreenshot(HardwareRenderingScreenshot.java:90)
	at org.robolectric.shadows.ShadowPixelCopy.takeScreenshot(ShadowPixelCopy.java:171)
	at org.robolectric.shadows.ShadowPixelCopy.request(ShadowPixelCopy.java:96)
	at org.robolectric.shadows.ShadowPixelCopy.request(ShadowPixelCopy.java:74)
	at android.view.PixelCopy.request(PixelCopy.java)
	at com.github.takahirom.robolectric.shadow.ExampleUnitTest.test$lambda$1(ExampleUnitTest.kt:33)
```

**Comment by hoisie** [comment]
I think we have to bump the preinstrumented jars version and rerelease them. We added an android interceptor for this recently.

https://github.com/robolectric/robolectric/blob/d48d2d408445103ac8b0c5be7a612b79e16d7e89/sandbox/src/main/java/org/robolectric/interceptors/AndroidInterceptors.java#L503

**Comment by ralf-at-android** [comment]
For this to work, you'll need the NioUtils interceptor, and also the recent Shadow changes to `ImageReaderNatives`, which is commit https://github.com/robolectric/robolectric/commit/491e1d3c1669a5ab219ebe1d806eaf734ea84b13 as well as the corresponding ImageReader.cpp changes in the .so.  
I'm not quite sure how the sync and release process works for robolectric, especially the native code stuff.

**Comment by desugar-64** [comment]
> I'm experiencing a ClassNotFoundException when using Pixel Copy with the snapshot version of Robolectric, specifically when robolectric.screenshot.hwrdr.native=true is set. This issue occurs during testing, resulting in a java.lang.ClassNotFoundException: java.nio.NioUtils error.
> 
> For a clearer picture, I've prepared a minimal example demonstrating the issue: [GitHub - takahirom/robolectric-snapshot-class-not-found-reproducer](https://github.com/takahirom/robolectric-snapshot-class-not-found-reproducer).
> 
> If there is any additional information I can provide, or if I have misunderstood any aspect of my setup, please let me know.
> 
> ```

> ```


When testing your sample project as is, and within my project, the Robolectric 4.12-SNAPSHOT version produces a slightly different error:


```stacktrace
java.lang.NoSuchMethodError: 'java.lang.invoke.CallSite org.robolectric.internal.bytecode.InvokeDynamicSupport.bootstrap(java.lang.invoke.MethodHandles$Lookup, java.lang.String, java.lang.invoke.MethodType, java.lang.invoke.MethodHandle)'
	at android.util.SparseArray.<init>(SparseArray.java:84)
	at android.util.SparseArray.<init>(SparseArray.java:74)
	at org.robolectric.shadows.ShadowAccessibilityNodeInfo.<clinit>(ShadowAccessibilityNodeInfo.java:55)
	at org.robolectric.Shadows.reset(Shadows.java:2727)
	at org.robolectric.android.internal.AndroidTestEnvironment.resetState(AndroidTestEnvironment.java:691)
	at org.robolectric.RobolectricTestRunner.lambda$finallyAfterTest$0(RobolectricTestRunner.java:315)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:86)
	at org.robolectric.RobolectricTestRunner.finallyAfterTest(RobolectricTestRunner.java:313)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:298)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:101)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by hoisie** [comment]
@desugar-64 I am working on this at the moment, the preinstrumented jar versions need to be bumped.

**Comment by hoisie** [comment]
FYI, the issue is that https://github.com/robolectric/robolectric/commit/44d1dec768cfd19927b8ef31e19352393aca4160 updates the invokedynamic delegators to include information about whether the method was originally native.

You can use the system property `robolectric.usePreinstrumentedJars=false`, or wait for the preinstrumented jars to be updated.

**Comment by desugar-64** [comment]
> robolectric.usePreinstrumentedJars=false

No problem, I'll give your workaround a shot while waiting for the complete fix.

**Comment by desugar-64** [comment]
hm, didn't work, I'll wait for the preinstrumented jars to be updated. 
> ./gradlew -Probolectric.usePreinstrumentedJars=false :core-lib:testDebugUnitTest

**Comment by desugar-64** [comment]
For this particular issue, I required Robolectric 4.12:  https://github.com/robolectric/robolectric/issues/8592#issuecomment-1885866207

**Comment by hoisie** [comment]
Try `-Drobolectric.usePreinstrumentedJars=false`?

**Comment by desugar-64** [comment]
> Try `-Drobolectric.usePreinstrumentedJars=false`?

I tried both, didn't help either.

**Comment by takahirom** [comment]
I tried it in the piper_597378927 branch (https://github.com/robolectric/robolectric/pull/8738) . 
The crash seems to be fixed, but the pixels are all zero. Is there an option I need to enable to get them drawn?

You can replicate this by copying it into ActivityScenarioTest.

```java
  @Test public void hasPixelWhenUseHardwareRendering() {
    System.setProperty("robolectric.screenshot.hwrdr.native", "true");
    try (ActivityScenario<TranscriptActivity> activityScenario = ActivityScenario.launch(
        TranscriptActivity.class)) {
      activityScenario.onActivity(activity -> {
        Window window = activity.getWindow();
        View decorView = window.getDecorView();
        View child = new View(activity);
        child.setBackgroundColor(0xFF0000FF);
        child.layout(0, 0, 100, 100);
        ((ViewGroup) decorView).addView(child);
        Espresso.onIdle();
        Bitmap viewDrawBitmap = Bitmap.createBitmap(decorView.getWidth(), decorView.getHeight(),
            Bitmap.Config.ARGB_8888);
        decorView.draw(new Canvas(viewDrawBitmap));

        Bitmap pixelCopyBitmap = Bitmap.createBitmap(decorView.getWidth(), decorView.getHeight(),
            Bitmap.Config.ARGB_8888);
        CountDownLatch latch = new CountDownLatch(1);
        PixelCopy.request(window, pixelCopyBitmap, copyResult -> latch.countDown(),
            new Handler(Looper.getMainLooper()));
        try {
          latch.await(1, TimeUnit.SECONDS);
        } catch (InterruptedException e) {
          throw new RuntimeException(e);
        }
        int pixelCopyBitmapPixel = pixelCopyBitmap.getPixel(0, 0);

        int viewDrawBitmapPixel = viewDrawBitmap.getPixel(0, 0);
        System.out.println("viewDrawBitmapPixel: " + Integer.toHexString(viewDrawBitmapPixel));
        System.out.println("pixelCopyBitmapPixel: " + Integer.toHexString(pixelCopyBitmapPixel));
        assertThat(pixelCopyBitmapPixel).isEqualTo(viewDrawBitmapPixel);
        pixelCopyBitmap.recycle();
      });
    }
  }
```

```
> Task :integration_tests:androidx_test:testDebugUnitTest
viewDrawBitmapPixel: ff0000ff
pixelCopyBitmapPixel: 0

expected: -16776961
but was : 0
expected: -16776961
but was : 0
	at org.robolectric.integrationtests.axt.ActivityScenarioTest.lambda$hasPixelWhenUseHardwareRendering$14(ActivityScenarioTest.java:296)
	at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$androidx-test-core-app-ActivityScenario(ActivityScenario.java:789)
	at androidx.test.core.app.ActivityScenario$$ExternalSyntheticLambda2.run(D8$$SyntheticClass)
	at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:799)
	at org.robolectric.integrationtests.axt.ActivityScenarioTest.hasPixelWhenUseHardwareRendering(ActivityScenarioTest.java:269)

org.robolectric.integrationtests.axt.ActivityScenarioTest > hasPixelWhenUseHardwareRendering FAILED
    expected: -16776961
    but was : 0
        at org.robolectric.integrationtests.axt.ActivityScenarioTest.lambda$hasPixelWhenUseHardwareRendering$14(ActivityScenarioTest.java:296)
        at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$androidx-test-core-app-ActivityScenario(ActivityScenario.java:789)
        at androidx.test.core.app.ActivityScenario$$ExternalSyntheticLambda2.run(D8$$SyntheticClass)
        at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:799)
        at org.robolectric.integrationtests.axt.ActivityScenarioTest.hasPixelWhenUseHardwareRendering(ActivityScenarioTest.java:269)

1 test completed, 1 failed
> Task :integration_tests:androidx_test:testDebugUnitTest FAILED
```

**Comment by hoisie** [comment]
@takahirom we can take a look at that test tomorrow and see what is happening.

**Comment by takahirom** [comment]
I'm pleased to report that the issue I previously raised with the [test code](https://github.com/robolectric/robolectric/issues/8081#issuecomment-1886067581) seems to have been resolved in `google` branch, and I'm now able to observe shadows on views as expected. 🎉 
Here's a screenshot for reference: 
![RoborazziCaptureTest checkViewWithElevationRendering 31 _compare](https://github.com/robolectric/robolectric/assets/1386930/ff9447b8-a1cd-456d-8786-19a989a14002).

However, I've encountered a minor issue regarding PixelCopy usage in conjunction with `ShadowPackageManager.addActivityIfNotPresent`. While using a Manifest file to add an Activity allows for successful screenshot captures, employing `ShadowPackageManager.addActivityIfNotPresent` results in a transparent image instead of the expected bitmap.

You can replicate this issue by copying this code into ActivityScenarioTest

```java
  static class CustomActivity extends Activity {
    @Override public void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      View view = new View(this);
      view.setBackgroundColor(0xffff0000);
      view.layout(0, 0, 100, 100);
      setContentView(view);
    }
  }

  @GraphicsMode(GraphicsMode.Mode.NATIVE) @Test
  public void hasPixelWhenUsingCustomAddingActivityHardwareRendering() {
    // **If we use false here, the test will pass.**
    System.setProperty("robolectric.screenshot.hwrdr.native", "false");
    Application application = ApplicationProvider.getApplicationContext();
    ((ShadowPackageManager) Shadows.shadowOf(
        application.getPackageManager())).addActivityIfNotPresent(
        new Intent(application, CustomActivity.class).resolveActivity(
            application.getPackageManager()));

    try (ActivityScenario<CustomActivity> activityScenario = ActivityScenario.launch(
        CustomActivity.class)) {
      activityScenario.onActivity(activity -> {
        Window window = activity.getWindow();
        View decorView = window.getDecorView();
        Espresso.onIdle();
        Bitmap viewDrawBitmap = Bitmap.createBitmap(decorView.getWidth(), decorView.getHeight(),
            Bitmap.Config.ARGB_8888);
        decorView.draw(new Canvas(viewDrawBitmap));

        Bitmap pixelCopyBitmap = Bitmap.createBitmap(decorView.getWidth(), decorView.getHeight(),
            Bitmap.Config.ARGB_8888);
        CountDownLatch latch = new CountDownLatch(1);
        PixelCopy.request(window, pixelCopyBitmap, copyResult -> latch.countDown(),
            new Handler(Looper.getMainLooper()));
        try {
          latch.await(1, TimeUnit.SECONDS);
        } catch (InterruptedException e) {
          throw new RuntimeException(e);
        }
        int pixelCopyBitmapPixel = pixelCopyBitmap.getPixel(0, 0);

        int viewDrawBitmapPixel = viewDrawBitmap.getPixel(0, 0);
        System.out.println("viewDrawBitmapPixel: " + Integer.toHexString(viewDrawBitmapPixel));
        System.out.println("pixelCopyBitmapPixel: " + Integer.toHexString(pixelCopyBitmapPixel));
        assertThat(pixelCopyBitmapPixel).isEqualTo(viewDrawBitmapPixel);
        pixelCopyBitmap.recycle();
      });
    }
  }
```

I would appreciate any guidance or suggestions on how to address this new issue.

**Comment by sergio-sastre** [comment]
> @takahirom Thanks for your confirmation. @oas004 @sergio-sastre Please try the latest 4.12.1 to check whether the shadow works as your expected. And feel free to reopen this issue if the issue still exists.

I’ve just checked it out and works as expected for the cases I’ve tested it. I’ll update the repo with the examples when I find time 😊

**Comment by dalapenko** [comment]
@utzcoz but test from comment @takahirom https://github.com/robolectric/robolectric/issues/8081#issuecomment-1968280166 still failed with 4.12.1

**Comment by takahirom** [comment]
I created an issue for the empty image problem caused by using addActivityIfNotPresent.
https://github.com/robolectric/robolectric/issues/8982

**Comment by hoisie** [comment]
I just wanted to mention there are a lot of rough edges related to HW rendering at the moment (more than we realized). I think it's okay to experiment with it, but I wouldn't recommend using it broadly until some issues get fixed and the APIs improve (i.e. removing that system property).

**Comment by yschimke** [comment]
@hoisie yep - taken on notice.

For me, it's overall a win.  https://github.com/google/horologist/pull/2188

![image](https://github.com/robolectric/robolectric/assets/231923/75bb0993-caee-4c46-a755-b98c78a8db26)

Probably the most obvious quirk to deal with is the transparency changes, which I think are valid.

![image](https://github.com/robolectric/robolectric/assets/231923/48f2fe95-19ad-46ab-a01c-8787d7146dec)

**Comment by hoisie** [comment]
@yschimke the alpha issues should be fixed in https://github.com/robolectric/robolectric/commit/c0c8e9869dcfeaa08b33d8ff2119e7b92ffd5006

**Comment by yschimke** [comment]
@hoisie even better it looks like a nice simplification in code.

**Comment by hoisie** [comment]
The alpha issue was fixed in 4.12.2. There are also other HW rendering improvements in 4.12.2. I am going to mark this closed.
